# Vectorization

In [16]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns
import math
import time

In [17]:
a=np.zeros(5)
print(a)
b=np.arange(0,6)
print(b)

[0. 0. 0. 0. 0.]
[0 1 2 3 4 5]


In [18]:
arr=np.arange(8)
meant=np.mean(arr)
mediant=np.median(arr)
summa=np.sum(arr)
print(arr)
print(f"Sum={summa}  median={mediant}   mean={meant}")
brr=arr**2
print(brr)

[0 1 2 3 4 5 6 7]
Sum=28  median=3.5   mean=3.5
[ 0  1  4  9 16 25 36 49]


In [19]:
# vector ops
a=np.array([1,2,3,4,5])
b=np.array([-1,-2,-3,-4,-5])
print(f"sum ={a+b}")
def my_dot(a, b): 
    """
   Compute the dot product of two vectors
 
    Args:
      a (ndarray (n,)):  input vector 
      b (ndarray (n,)):  input vector with same dimension as a
    
    Returns:
      x (scalar): 
    """
    x=0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x



sum =[0 0 0 0 0]


In [21]:
# time difference between the vectorised method and  the regular one without using vectors

np.random.seed(1)
a = np.random.rand(10000000)  # very large arrays
b = np.random.rand(10000000)

tic = time.time()  # capture start time
c = np.dot(a, b)
toc = time.time()  # capture end time

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

tic = time.time()  # capture start time
c = my_dot(a,b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a);del(b)

np.dot(a, b) =  2501072.5817
Vectorized version duration: 5.2381 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 2876.2720 ms 


# Multiple variable linear regression

In [22]:
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

In [33]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init shape: (4,), b_init type: <class 'float'>


In [31]:
def prediction(x,w,b):
    p=np.dot(x,w)+b
    return p
x_vec=X_train[0,:]
print(x_vec)

[2104    5    1   45]


In [32]:
def compute_cost(x,y,w,b):
    m=x.shape[0]
    cost=0.0

    for i in range(m):
        f_wb_i=np.dot(x[i],w)+b
        cost=cost+(f_wb_i-y[i])**2
    cost=cost/(2*m)
    return cost